typography_spectrum: 0.8362401260528713
color:
  brandStrength: 0.4001738599035889
  lightness: 0.1462999116629362
  saturation: 0.6468750620260835
  rhythmicContrast: 0.03142075682990253
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.7991102756932378
author:
  name: Matthew Aldrich
  email: matt@bigbadpixel.com
logo: null
name: BIGBADPIXEL
title: Digital Design
description: helping the world..... one pixel at a time!
