layout_spectrum: 0.49370459001511335
typography_spectrum: 0.6340568533632904
color:
  brandStrength: 0.029587487690150738
  lightness: 0.6243110278155655
  saturation: 0.10281299892812967
  rhythmicContrast: 0.6280328573193401
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
author:
  name: Matthew Aldrich
  email: matt@bigbadpixel.com
logo: null
name: BIGBADPIXEL
title: Digital Design
description: helping the world..... one pixel at a time!
